# This file is a template, and might need editing before it works on your project.
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    
# build:
#   stage: build
#   script: 
#     - npm install
#     - ./node_modules/.bin/gatsby build --prefix-paths
#   rules:
#     - if: $CI_MERGE_REQUEST_ID 

pages:
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' 
